### ISSUE TITLE
android.view.ViewGroup.debug shadows org.scaloid.common.debug

### ISSUE THREAD

**Issue by PkmX** [pocorall/scaloid#112]
This causes inconveniences when calling `debug` to write strings to logcat in the DSL, as we will have to qualify the `org.scaloid.common.debug`.

**Comment by pocorall** [comment]
I was misunderstood the problem. I thought `ViewGroup.debug` is shadowed by `scaloid.common.debug`.

But, actual problem is the opposite case. This is relatively easy. Use `r2String` to explicitly convert a resource id to the corresponding String resource.

`debug(R.string.mystr.r2String) \\ will call org.scaloid.common.debug`

**Comment by PkmX** [comment]
Converting to `String` would not work as `org.scaloid.common.debug` is still shadowed by `ViewGroup.debug`, so it is not considered for overloading at all. It will just give an error saying that it is given a `String` while expecting an `Int`.

**Comment by pocorall** [comment]
I added an overloading function to `TraitViewGroup`.
