### ISSUE TITLE
org.scaloid.common.runOnUiThread

### ISSUE THREAD

**Issue by PkmX** [pocorall/scaloid#118]
`org.scaloid.common.runOnUiThread` currently has the signature:

```scala
def runOnUiThread[T >: Null](f: ⇒ T): T
```

If it is called with a block that returns `Unit`, and since `Unit <: AnyVal` and `Null <: AnyRef`, Scala can only infer `T` to be `Any`, which gives an annoying warning message that `Any` is inferred if compiling with `-Xlint` enabled.

The real issue here however is that I believe *returning the result of `f` or `null` depending on whether `runOnUiThread` is called on the UI thread* is a misdesign. The caller either calls this function from a non-UI thread to perform side effects on the UI thread, and in this case `f` should return `Unit`. If the caller is already on the UI thread, he can just call `f` directly to collect the result. Also, returning `null` is basically asking for `NullPointerException` if the user is not careful about this.

Therefore, my proposal is to change the signature to the simpler:

```scala
def runOnUiThread(f: => Unit): Unit
```

and remove the return statements so that `runOnUiThread` is only used to perform the side effects of `f`. I can send a pull request if you are okay with this change.

**Comment by tvierling** [comment]
Yes, this would be appropriate. Any by-name block should work fine with this signature.

**Comment by tvierling** [comment]
Come to think of it, simply refitting this to return a `Future` might not be such a bad idea; truly asynchronous callers can just discard it upon the return of `runOnUiThread()`. Hm, I'll look into this momentarily.

**Comment by PkmX** [comment]
> Come to think of it, simply refitting this to return a `Future` might not be such a bad idea; truly asynchronous callers can just discard it upon the return of `runOnUiThread()`.

I think it's better to overload it (untested):

```scala
  def runOnUiThread(f: => Unit): Unit = {
    if (uiThread == Thread.currentThread) {
      f
    } else {
      handler.post(new Runnable() {
        def run(): Unit = f
      })
    }
  }

  def runOnUiThread[T](f: => T): Future[T] = {
    val p = Promise[T]()
    if (uiThread == Thread.currentThread) {
      p.complete(Try(f))
    } else {
      runOnUiThread {
        p.complete(Try(f))
      }
    }
    p.future
  }
```

**Comment by PkmX** [comment]
> Come to think of it, simply refitting this to return a `Future` might not be such a bad idea; truly asynchronous callers can just discard it upon the return of `runOnUiThread()`.

Sounds good! This also allows the UI thread to signal failure in case of exceptions. Untested code:

```scala
  def runOnUiThread[T](f: => T): Future[T] = {
    val p = Promise[T]()
    if (uiThread == Thread.currentThread) {
      p.complete(Try(f))
    } else {
      runOnUiThread {
        p.complete(Try(f))
      }
    }
    p.future
  }
```

**Comment by tvierling** [comment]
Yeah, that's pretty much it (haven't had a chance to give it a whirl yet). The question is whether it's significant overhead to add the extra object churn, or if it's slim enough not to need an alternative.

(You can't just overload => T and => Unit because both erase to Function1. Plus, since almost every Scala statement is an expression with a type other than Unit, autodetecting the intent is not really possible even by adding a Manifest. You'd need a different method name for the 'slimmer' version.)

**Comment by tvierling** [comment]
(Note, there is a `Future.fromTry()` for an extra micro-optimization.)

**Comment by PkmX** [comment]
> (You can't just overload => T and => Unit because both erase to Function1. Plus, since almost every Scala statement is an expression with a type other than Unit, autodetecting the intent is not really possible even by adding a Manifest. You'd need a different method name for the 'slimmer' version.)

Yeah, that's what I figured right after I posted that (now-deleted) comment. Eventually I decided against the `=> Unit` overload as this would not allow the UI thread to signal exception.

**Comment by tvierling** [comment]
There is a functional change with this design, to keep in mind. By switching to `Try`, exceptions do not get propagated up the UI thread. While this may be desirable in some cases, it might make debugging a little weirder. That makes me think the original solution (returning `Unit`) and a new, separate method returning `Future` might be the best option.

And of course, there's one other 'slimness' concern about using `Future`: dexopt is going to pull in more code when it's used. However, since this solution uses static `Promise` objects and doesn't actually spawn an `Executor`, it shouldn't be susceptible to the problems described by:

http://blog.scaloid.org/2013/11/using-scalaconcurrentfuture-in-android.html

**Comment by pocorall** [comment]
What a nice discussion! In my opinion, macro could help merge the slimmer version and the full version using `Future`.

    val f:Future[Int] = runOnUiThread { returnsInt() }

    runOnUiThread { returnsInt() } // returns null if nothing receives it

**Comment by tvierling** [comment]
The reason I didn't go the macro route with the above pull request is because when you have a `Future`, you need to ensure that you do something with it (because exceptions will be discarded if you don't). That makes run vs. eval a conscious choice rather than a side effect of the call structure.
